FROM nvidia/cuda:12.4.0-runtime-ubuntu22.04
# Install python 3.11 and set it as the default python version.
RUN apt update && apt install -y python3.11 python3.11-dev python3-pip
RUN update-alternatives --install /usr/bin/python3 python /usr/bin/python3.11 1

# Set the PYTHONPATH environment variable
ENV PYTHONPATH=/usr/src/app

# Install the requirements
COPY ./src/inference_pipeline/requirements.txt .
RUN pip install -r requirements.txt

# Copy the rest of the application code
COPY ./src/core ./core
COPY ./src/inference_pipeline .

# Command to run the inference pipeline script
CMD ["python3", "main.py"]
